version: "3"
services:
  cscmsboard:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    restart: always
    depends_on:
      - cscmsboard
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"